### ISSUE TITLE
Without changing select area image not cropped

### ISSUE THREAD

**Issue by bilal-pyntail** [Andrew8xx8/awesome-cropper#12]
I have facing an issue, without changing or moving the selected area if I pressed apply then empty image cropped.

how can I cropped I mage to the default selected area if I do not change or move selected area ?

**Comment by shivapendem** [comment]
In drawimage after 
 oWidth = img.attr('data-original-width');
oHeight = img.attr('data-original-height');

add 
if(oWidth===undefined)
       {
          oWidth =900;
          oHeight =900;
       }
as per my requirement its 900, you can change it to your requirement from 400 to 1200, but i suggest 900.

this creates the default image and once you select the concern image changes will apply.

**Comment by Andrew8xx8** [comment]
Fixed. Please check out a new version
